# Generated by Django 6.0.8 on 2026-08-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=100, verbose_name='นามสกุล')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('gender', models.CharField(choices=[('M', 'ชาย'), ('F', 'หญิง'), ('O', 'อื่น ๆ')], max_length=1, verbose_name='เพศ')),
                ('birth_date', models.DateField(verbose_name='วันเกิด')),
                ('department', models.CharField(choices=[('IT', 'เทคโนโลยีสารสนเทศ'), ('HR', 'ทรัพยากรบุคคล'), ('FIN', 'การเงินและบัญชี'), ('MKT', 'การตลาด'), ('OPS', 'ปฏิบัติการ'), ('ADMIN', 'ธุรการ')], max_length=20, verbose_name='แผนก')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='เงินเดือน')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('status', models.CharField(choices=[('active', 'ทำงานอยู่'), ('leave', 'ลางาน'), ('inactive', 'พ้นสภาพ')], default='active', max_length=20, verbose_name='สถานะ')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='รูปภาพ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
            options={
                'verbose_name': 'พนักงาน',
                'verbose_name_plural': 'พนักงาน',
                'ordering': ['-created_at'],
            },
        ),
    ]
